version: '2'
services:
    plagui-app:
        image: plagui
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://plagui-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=plagUI
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    plagui-mongodb:
        extends:
            file: mongodb.yml
            service: plagui-mongodb
